### ISSUE TITLE
Connecting to DB2/Z throws licensing error

### ISSUE THREAD

**Issue by shreyas-shankar** [ibmdb/python-ibmdbsa#90]
Hello

I am trying to connect to a DB2/Z instance. Here is the code that I use

```
uri = "db2+ibm_db://user:password@host:port/db"
engine = create_engine(uri)
connection = engine.connect()
```
I've also tried by changing the driver to `ibm_db_sa`.

Here is the error that I get
```
ProgrammingError: (ibm_db_dbi.ProgrammingError) ibm_db_dbi::ProgrammingError: Exception('[IBM][CLI Driver] SQL1598N  An attempt to connect to the database server failed because of a licensing problem.  SQLSTATE=42968 SQLCODE=-1598')
(Background on this error at: http://sqlalche.me/e/13/f405)
```
I have confirmed that the connection to the database works when using a JDBC driver. 

Can I please get some help with this issue?

**Comment by amukherjee28** [comment]
Hi,

Connection to Non LUW servers (DB2 for ZOS and DB2 for I-series) using the driver would require db2 license.

This license needs to be placed in the license folder of the driver used while connection to ensure successful connect.
In case you are using the default driver the look for the clidriver folder inside the site-packages directory and then put the license in the license folder of the clidriver.
In case you are using a different driver, then navigate to the same in order to have the license file placed.

JDBC driver uses a different licensing mechanism to connect to ZOS and hence it works for you.
Python Alchemy driver uses clidriver for establishing connection and hence the licensing mechanism is different.

Thanks.

**Comment by shreyas-shankar** [comment]
Thank you. I was able to add a license and connect to the Z/OS system.
